[project]
name = "horrazon-ai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.140.13",
    "google-generativeai>=0.8.6",
    "httpx>=0.28.1",
    "httpx-sse>=0.4.3",
    "langchain-google-genai>=4.3.2",
    "langgraph>=1.2.10",
    "prompt-toolkit>=3.0.53",
    "pydantic>=2.13.4",
    "rich>=15.0.0",
    "uvicorn>=0.52.0",
]
